version: '3'

services:

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: cargo watch -c -x run
    environment:
      - PORT=${GATEWAY_PORT}
