version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  messages:
    build:
      context: ./messages
      dockerfile: dockerfile
    ports:
      - ${MESSAGES_PORT}:${MESSAGES_PORT}
    volumes:
      - ./messages/src:/usr/src/app/src
    command: cargo watch -c -x run
    environment:
      - PORT=${MESSAGES_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: cargo watch -c -x run
    environment:
      - PORT=${GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
